grails-app/domain/com/musify/Artist.groovy
package com.musify

class Artist {
	
	String name
	Integer year
	
	static hasMany = [styles:Style, members: People, related: Artist]

    static constraints = {
    }
	
	String toString(){
		return "${name}, ${year}"
	}
}

grails-app/controllers/com/musify/ArtistController.groovy
package com.musify



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ArtistController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Artist.list(params), model:[artistInstanceCount: Artist.count()]
    }
	
	def listByStyle(){
		render view:"/artist/list",  model:['artistList' : Artist.list(),'styles': Style.list()]
	}
	
    def show(Artist artistInstance) {
        respond artistInstance
    }

    def create() {
        respond new Artist(params)
    }

    @Transactional
    def save(Artist artistInstance) {
        if (artistInstance == null) {
            notFound()
            return
        }

        if (artistInstance.hasErrors()) {
            respond artistInstance.errors, view:'create'
            return
        }

        artistInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'artist.label', default: 'Artist'), artistInstance.id])
                redirect artistInstance
            }
            '*' { respond artistInstance, [status: CREATED] }
        }
    }

    def edit(Artist artistInstance) {
        respond artistInstance
    }

    @Transactional
    def update(Artist artistInstance) {
        if (artistInstance == null) {
            notFound()
            return
        }

        if (artistInstance.hasErrors()) {
            respond artistInstance.errors, view:'edit'
            return
        }

        artistInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Artist.label', default: 'Artist'), artistInstance.id])
                redirect artistInstance
            }
            '*'{ respond artistInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Artist artistInstance) {

        if (artistInstance == null) {
            notFound()
            return
        }

        artistInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Artist.label', default: 'Artist'), artistInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'artist.label', default: 'Artist'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/artist/_form.gsp
<%@ page import="com.musify.Artist" %>

<style>
	.select-multiple {
        width: 400px;
    }
</style>    

<div class="fieldcontain ${hasErrors(bean: artistInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="artist.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${artistInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: artistInstance, field: 'year', 'error')} required">
	<label for="year">
		<g:message code="artist.year.label" default="Year" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="year" type="number" value="${artistInstance.year}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: artistInstance, field: 'styles', 'error')} ">
	<label for="styles">
		<g:message code="artist.styles.label" default="Styles" />
		
	</label>
	<g:select name="styles" from="${com.musify.Style.list()}" multiple="multiple" optionKey="id" size="5" value="${artistInstance?.styles*.id}" class="select-multiple many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: artistInstance, field: 'members', 'error')} ">
	<label for="members">
		<g:message code="artist.members.label" default="Members" />
		
	</label>
	<g:select name="members" from="${com.musify.People.list()}" multiple="multiple" optionKey="id" size="5" value="${artistInstance?.members*.id}" class="select-multiple many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: artistInstance, field: 'related', 'error')} ">
	<label for="related">
		<g:message code="artist.related.label" default="Related" />
		
	</label>
	<g:select name="related" from="${com.musify.Artist.list() - artistInstance}" multiple="multiple" optionKey="id" size="5" value="${artistInstance?.related*.id}" class="select-multiple many-to-many"/>

</div>

grails-app/views/artist/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'artist.label', default: 'Artist')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-artist" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-artist" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${artistInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${artistInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:artistInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/artist/edit.gsp
<%@ page import="com.musify.Artist" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'artist.label', default: 'Artist')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-artist" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-artist" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${artistInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${artistInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:artistInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${artistInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/artist/index.gsp
<%@ page import="com.musify.Artist" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'artist.label', default: 'Artist')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-artist" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-artist" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'artist.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="year" title="${message(code: 'artist.year.label', default: 'Year')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${artistInstanceList}" status="i" var="artistInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${artistInstance.id}">${fieldValue(bean: artistInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: artistInstance, field: "year")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${artistInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/artist/list.gsp
<%@ page import="com.musify.Artist" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'artist.label', default: 'Artist')}" />
		<title>Artist List by Style</title>
	</head> 		
	<body>
		<a href="#list-artist" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
	<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			</ul>
		</div>
		<div id="list-artist" class="content scaffold-list" role="main">
			<h1>Artist List by Style</h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:each in="${styles}" var="style">
					<h1>Style: ${style}</h1>
					<table>
					<thead>
							<tr>
								<g:sortableColumn property="name" title="Artists" />
							
							</tr>
						</thead>
						<tbody>
							<g:each in="${artistList}" status="i" var="artistInstance">
								<g:if test="${artistInstance.styles.contains(style)}">
									<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
								
										<td><g:link action="show" id="${artistInstance.id}">${fieldValue(bean: artistInstance, field: "name")}</g:link></td>
									</tr>
								</g:if>
			
							</g:each>
						</tbody>
					</table>
			</g:each>
		</div>
	</body>
</html>

grails-app/views/artist/show.gsp
<%@ page import="com.musify.Artist" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'artist.label', default: 'Artist')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-artist" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-artist" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list artist">
			
				<g:if test="${artistInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="artist.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${artistInstance}" field="name"/></span>
					
				</li>
				</g:if>

				<g:if test="${artistInstance?.year}">
				<li class="fieldcontain">
					<span id="year-label" class="property-label"><g:message code="artist.year.label" default="Year" /></span>
					
						<span class="property-value" aria-labelledby="year-label"><g:fieldValue bean="${artistInstance}" field="year"/></span>
					
				</li>
				</g:if>

				<g:if test="${artistInstance?.styles}">
				<li class="fieldcontain">
					<span id="styles-label" class="property-label"><g:message code="artist.styles.label" default="Styles" /></span>
					
						<g:each in="${artistInstance.styles}" var="s">
						<span class="property-value" aria-labelledby="styles-label"><g:link controller="style" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
												
				<g:if test="${artistInstance?.members}">
				<li class="fieldcontain">
					<span id="members-label" class="property-label"><g:message code="artist.members.label" default="Members" /></span>
					
						<g:each in="${artistInstance.members}" var="m">
						<span class="property-value" aria-labelledby="members-label"><g:link controller="people" action="show" id="${m.id}">${m?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${artistInstance?.related}">
				<li class="fieldcontain">
					<span id="related-label" class="property-label"><g:message code="artist.related.label" default="Related" /></span>
					
						<g:each in="${artistInstance.related}" var="r">
						<span class="property-value" aria-labelledby="related-label"><g:link controller="artist" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:artistInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${artistInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>