grails-app/domain/com/musify/People.groovy
package com.musify

class People {
	
	String name
	Integer years
	
    static constraints = {
    }
	
	String toString(){
		return "${name}, ${years}"
	}
}

grails-app/controllers/com/musify/PeopleController.groovy
package com.musify



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PeopleController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond People.list(params), model:[peopleInstanceCount: People.count()]
    }

    def show(People peopleInstance) {
        respond peopleInstance
    }

    def create() {
        respond new People(params)
    }

    @Transactional
    def save(People peopleInstance) {
        if (peopleInstance == null) {
            notFound()
            return
        }

        if (peopleInstance.hasErrors()) {
            respond peopleInstance.errors, view:'create'
            return
        }

        peopleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'people.label', default: 'People'), peopleInstance.id])
                redirect peopleInstance
            }
            '*' { respond peopleInstance, [status: CREATED] }
        }
    }

    def edit(People peopleInstance) {
        respond peopleInstance
    }

    @Transactional
    def update(People peopleInstance) {
        if (peopleInstance == null) {
            notFound()
            return
        }

        if (peopleInstance.hasErrors()) {
            respond peopleInstance.errors, view:'edit'
            return
        }

        peopleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'People.label', default: 'People'), peopleInstance.id])
                redirect peopleInstance
            }
            '*'{ respond peopleInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(People peopleInstance) {

        if (peopleInstance == null) {
            notFound()
            return
        }

        peopleInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'People.label', default: 'People'), peopleInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'people.label', default: 'People'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/people/_form.gsp
<%@ page import="com.musify.People" %>



<div class="fieldcontain ${hasErrors(bean: peopleInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="people.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${peopleInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: peopleInstance, field: 'years', 'error')} required">
	<label for="years">
		<g:message code="people.years.label" default="Years" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="years" type="number" value="${peopleInstance.years}" required=""/>

</div>

grails-app/views/people/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'people.label', default: 'People')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-people" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-people" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${peopleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${peopleInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:peopleInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/people/edit.gsp
<%@ page import="com.musify.People" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'people.label', default: 'People')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-people" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-people" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${peopleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${peopleInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:peopleInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${peopleInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/people/index.gsp
<%@ page import="com.musify.People" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'people.label', default: 'People')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-people" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-people" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'people.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="years" title="${message(code: 'people.years.label', default: 'Years')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${peopleInstanceList}" status="i" var="peopleInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${peopleInstance.id}">${fieldValue(bean: peopleInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: peopleInstance, field: "years")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${peopleInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/people/show.gsp
<%@ page import="com.musify.People" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'people.label', default: 'People')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-people" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-people" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list people">
			
				<g:if test="${peopleInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="people.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${peopleInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${peopleInstance?.years}">
				<li class="fieldcontain">
					<span id="years-label" class="property-label"><g:message code="people.years.label" default="Years" /></span>
					
						<span class="property-value" aria-labelledby="years-label"><g:fieldValue bean="${peopleInstance}" field="years"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:peopleInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${peopleInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>